/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KXN444LrJlU
 */
import { Button } from '@/components/ui/button';

export function Hero() {
	return (
		<div className="grid grid-rows-[auto,1fr,gap-y-0] w-full max-w-2xl px-4 py-12 items-center space-y-12">
			<div className="flex flex-col items-center space-y-2">
				<h1 className="text-2xl font-bold">JSON Canvas to Mermaid</h1>
				<p className="text-sm text-gray-500 dark:text-gray-400">
					Drag and drop a JSON Canvas file to convert it to Mermaid
				</p>
			</div>
			<div className="flex flex-col border border-gray-200 border-dashed rounded-lg dark:border-gray-800">
				<div
					className="grid w-full h-[200px] items-center text-center text-sm text-gray-500 dark:text-gray-400"
					style={{
						gridTemplateColumns: '1fr',
					}}
				>
					<span className="flex items-center justify-center w-full space-x-2">
						<FileIcon className="w-6 h-6" />
						<span>
							Drag and drop your file here or <Button size="sm">Browse</Button>
						</span>
					</span>
				</div>
				<input
					aria-label="File input"
					className="sr-only"
					type="file"
				/>
			</div>
			<div className="flex flex-col border border-gray-200 rounded-lg dark:border-gray-800">
				<div
					className="grid w-full p-4 text-sm text-gray-500 dark:text-gray-400"
					style={{
						gridTemplateColumns: '1fr',
					}}
				>
					<div className="flex items-center justify-center w-full space-x-2">
						<CodeIcon className="w-6 h-6" />
						<pre className="w-full overflow-auto text-left">
							{`<xml>
            <name>John</name>
            <age>30</age>
          </xml>`}
						</pre>
					</div>
				</div>
			</div>
			<Button>Convert</Button>
		</div>
	);
}

function FileIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
			<polyline points="14 2 14 8 20 8" />
		</svg>
	);
}

function CodeIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<polyline points="16 18 22 12 16 6" />
			<polyline points="8 6 2 12 8 18" />
		</svg>
	);
}
